apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api-server-deployment
  namespace: kawaljeet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-api-server
  template:
    metadata:
      labels:
        app: my-api-server
    spec:
      containers:
        - name: my-api-server-container
          image: fastapi-scrambler
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
